export { default as apiClient, type ApiResponse, isApiError } from './client'
export { eventsApi } from './events'
export { institutesApi } from './institutes'
export * from './types'
export { usersApi } from './users'
